name       : ypkg
homepage   : https://github.com/solus-project/ypkg
version    : 16
release    : 69
source     :
    - https://github.com/solus-project/ypkg/archive/v16.tar.gz : d6473db660e978f3046c73c5849f6882b29b834034d1f16a9efa8381222d71a4
license    :
    - GPL-3.0
summary    : Modern, declarative, structured build format
component  : system.devel
builddeps  :
    - python-setuptools
rundeps    :
    - python-configobj
    - pyyaml
    - fakeroot
    - ruamel_yaml
description: |
    ypkg is the build tool of choice for Solus. Simply put, it is a tool to
    convert a build process into a packaging operation.
setup      : |
    %patch -p1 < $pkgfiles/0001-examine-Inspect-all-of-the-files-in-parallel.patch
    %python_setup
install    : |
    %python_install
    # These are going to be replaced by ypkg-tools
    install -D -m 00755 scripts/yupdate.py $installdir/usr/share/ypkg/yupdate.py
    install -m 00755 scripts/ybump.py $installdir/usr/share/ypkg/.
    # Stop eopkg check freaking out
    find $installdir -name "*.pyc" |xargs rm -v
