name       : ypkg
version    : 30
release    : 141
source     :
    - git|https://github.com/getsolus/ypkg.git : d972ef82a274929c73bf2e170c0b1ed0eb678930
license    : GPL-3.0-or-later
component  : system.devel
summary    : Modern, declarative, structured build format
description: |
    ypkg is the build tool of choice for Solus. Simply put, it is a tool to convert a build process into a packaging operation.
builddeps  :
    - python-setuptools
rundeps    :
    - fakeroot
    - python-configobj
    - pyyaml
    - ruamel_yaml
setup      : |
    %patch -p1 < $pkgfiles/profile-intru-ldflags.patch
    %python_setup
install    : |
    %python_install
    # These are going to be replaced by ypkg-tools
    install -D -d -m 00755 $installdir/usr/share/ypkg
    ln -sv ../../bin/yupdate $installdir/usr/share/ypkg/yupdate.py
    ln -sv ../../bin/ybump $installdir/usr/share/ypkg/ybump.py
