name       : ypkg
version    : 30
release    : 136
source     :
    - git|https://github.com/getsolus/ypkg.git : 902e8be1a7e6d49999ee9b971c1b22a21b4c2a80
license    : GPL-3.0-or-later
component  : system.devel
summary    : Modern, declarative, structured build format
description: |
    ypkg is the build tool of choice for Solus. Simply put, it is a tool to convert a build process into a packaging operation.
builddeps  :
    - python-setuptools
rundeps    :
    - fakeroot
    - python-configobj
    - pyyaml
    - ruamel_yaml
setup      : |
    %patch -p1 < $pkgfiles/teach-qml-cache-about-spaces.patch
    %python_setup
install    : |
    %python_install
    # These are going to be replaced by ypkg-tools
    install -D -d -m 00755 $installdir/usr/share/ypkg
    ln -sv ../../bin/yupdate $installdir/usr/share/ypkg/yupdate.py
    ln -sv ../../bin/ybump $installdir/usr/share/ypkg/ybump.py
