name       : ypkg
version    : 30
release    : 146
source     :
    - git|https://github.com/getsolus/ypkg.git : 0f82f5407920d6f989299c7838aecb48a5b29bd1
license    : GPL-3.0-or-later
component  : system.devel
summary    : Modern, declarative, structured build format
description: |
    ypkg is the build tool of choice for Solus. Simply put, it is a tool to convert a build process into a packaging operation.
builddeps  :
    - python-setuptools
rundeps    :
    - fakeroot
    - python-configobj
    - pyyaml
    - ruamel_yaml
setup      : |
    %python_setup
install    : |
    %python_install
    # These are going to be replaced by ypkg-tools
    install -Ddm00755 $installdir/usr/share/ypkg
    ln -sv ../../bin/yupdate $installdir/usr/share/ypkg/yupdate.py
    ln -sv ../../bin/ybump $installdir/usr/share/ypkg/ybump.py
