name       : ypkg
homepage   : https://github.com/solus-project/ypkg
version    : 14
release    : 63
source     :
    - https://github.com/solus-project/ypkg/archive/v14.tar.gz : b411643dd1b125ae64af7b8bec742b4c4eaf3324ec657acf357ff01a76eaf8d7
license    :
    - GPL-3.0
summary    : Modern, declarative, structured build format
component  : system.devel
builddeps  :
    - python-setuptools
rundeps    :
    - python-configobj
    - python-configobj
    - pyyaml
    - ruamel_yaml
description: |
    ypkg is the build tool of choice for Solus. Simply put, it is a tool to
    convert a build process into a packaging operation.
setup      : |
    %python_setup
install    : |
    %python_install
    # These are going to be replaced by ypkg-tools
    install -D -m 00644 scripts/yupdate.py $installdir/usr/share/ypkg/yupdate.py
    install -m 00644 scripts/ybump.py $installdir/usr/share/ypkg/.
    # Stop eopkg check freaking out
    find $installdir -name "*.pyc" |xargs rm -v
