name       : ypkg
homepage   : https://github.com/solus-project/ypkg
version    : '26'
release    : 111
source     :
    - git|https://github.com/solus-project/ypkg.git : d4c1423629fb120fcb29a259b8a78ba023cc83db
license    :
    - GPL-3.0
summary    : Modern, declarative, structured build format
component  : system.devel
builddeps  :
    - python-setuptools
rundeps    :
    - python-configobj
    - pyyaml
    - fakeroot
    - ruamel_yaml
description: |
    ypkg is the build tool of choice for Solus. Simply put, it is a tool to
    convert a build process into a packaging operation.
setup      : |
    %python_setup
install    : |
    %python_install
    # These are going to be replaced by ypkg-tools
    install -D -d -m 00755 $installdir/usr/share/ypkg
    ln -sv ../../bin/yupdate $installdir/usr/share/ypkg/yupdate.py
    ln -sv ../../bin/ybump $installdir/usr/share/ypkg/ybump.py
